package com.github.shby0527.tgbot.dao;

import com.github.shby0527.tgbot.entities.InfoTags;

public interface InfoTagsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_tags
     *
     * @mbg.generated Tue Jul 19 12:04:09 CST 2022
     */
    int insert(InfoTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_tags
     *
     * @mbg.generated Tue Jul 19 12:04:09 CST 2022
     */
    int insertSelective(InfoTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_tags
     *
     * @mbg.generated Tue Jul 19 12:04:09 CST 2022
     */
    InfoTags selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_tags
     *
     * @mbg.generated Tue Jul 19 12:04:09 CST 2022
     */
    int updateByPrimaryKeySelective(InfoTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_tags
     *
     * @mbg.generated Tue Jul 19 12:04:09 CST 2022
     */
    int updateByPrimaryKey(InfoTags record);
}