package com.github.shby0527.tgbot.dao;

import com.github.shby0527.tgbot.entities.TagFoImgKey;

public interface TagToImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_fo_img
     *
     * @mbg.generated Tue Jul 19 12:04:09 CST 2022
     */
    int insert(TagFoImgKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_fo_img
     *
     * @mbg.generated Tue Jul 19 12:04:09 CST 2022
     */
    int insertSelective(TagFoImgKey record);
}