package com.github.shby0527.tgbot.dao;

import com.github.shby0527.tgbot.entities.TagFoImgKey;
import com.github.shby0527.tgbot.entities.TagPopular;
import org.apache.ibatis.annotations.Param;

import java.util.Collection;
import java.util.List;

public interface TagToImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_fo_img
     *
     * @mbg.generated Tue Jul 19 12:04:09 CST 2022
     */
    int insert(TagFoImgKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_fo_img
     *
     * @mbg.generated Tue Jul 19 12:04:09 CST 2022
     */
    int insertSelective(TagFoImgKey record);

    List<Long> tagsIdToImageId(@Param("tagIds") Collection<Long> tagIds);


    Collection<TagPopular> getTopOfTags(@Param("limit") int limit);
}