package com.github.shby0527.tgbot.dao;

import com.github.shby0527.tgbot.entities.TgUploaded;

public interface TgUploadedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_uploaded
     *
     * @mbg.generated Tue Jul 19 12:04:09 CST 2022
     */
    int insert(TgUploaded record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_uploaded
     *
     * @mbg.generated Tue Jul 19 12:04:09 CST 2022
     */
    int insertSelective(TgUploaded record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_uploaded
     *
     * @mbg.generated Tue Jul 19 12:04:09 CST 2022
     */
    TgUploaded selectByPrimaryKey(Long imgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_uploaded
     *
     * @mbg.generated Tue Jul 19 12:04:09 CST 2022
     */
    int updateByPrimaryKeySelective(TgUploaded record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_uploaded
     *
     * @mbg.generated Tue Jul 19 12:04:09 CST 2022
     */
    int updateByPrimaryKey(TgUploaded record);
}