package com.github.shby0527.tgbot.dao;

import com.github.shby0527.tgbot.entities.Userjobs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserJobsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserJobs
     *
     * @mbg.generated Wed Aug 17 17:25:49 CST 2022
     */
    int insert(Userjobs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserJobs
     *
     * @mbg.generated Wed Aug 17 17:25:49 CST 2022
     */
    int insertSelective(Userjobs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserJobs
     *
     * @mbg.generated Wed Aug 17 17:25:49 CST 2022
     */
    Userjobs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserJobs
     *
     * @mbg.generated Wed Aug 17 17:25:49 CST 2022
     */
    int updateByPrimaryKeySelective(Userjobs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserJobs
     *
     * @mbg.generated Wed Aug 17 17:25:49 CST 2022
     */
    int updateByPrimaryKey(Userjobs record);


    List<Userjobs> getAllJobs();

    int updateNextTruck(@Param("id") Long id, @Param("nextTruck") Long nextTruck);

    List<Userjobs> getMyChatJobs(@Param("userId") Long userId, @Param("chatId") Long chatId);
}