package com.github.shby0527.tgbot.dao;

import com.github.shby0527.tgbot.entities.Userinfo;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbg.generated Tue Aug 16 17:58:22 CST 2022
     */
    int insert(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbg.generated Tue Aug 16 17:58:22 CST 2022
     */
    int insertSelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbg.generated Tue Aug 16 17:58:22 CST 2022
     */
    Userinfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbg.generated Tue Aug 16 17:58:22 CST 2022
     */
    int updateByPrimaryKeySelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbg.generated Tue Aug 16 17:58:22 CST 2022
     */
    int updateByPrimaryKey(Userinfo record);
}