package com.github.shby0527.tgbot.entities;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * 表名: info_tags
 * 创建时间: 2022-07-19 12:04:09
 */
@Data
public class InfoTags implements Serializable {
    /**
     * Table:     info_tags
     * Column:    id
     * Nullable:  false
     */
    private Long id;

    /**
     * 标签
     *
     * Table:     info_tags
     * Column:    tag
     * Nullable:  false
     */
    private String tag;

    /**
     * Table:     info_tags
     * Column:    ctime
     * Nullable:  true
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table info_tags
     *
     * @mbg.generated Tue Jul 19 12:04:09 CST 2022
     */
    private static final long serialVersionUID = 1L;
}