package com.github.shby0527.tgbot.entities;

import lombok.Data;

import java.io.Serializable;

@Data
public class TagFoImgKey implements Serializable {
    /**
     * Table:     tag_fo_img
     * Column:    imgId
     * Nullable:  false
     */
    private Long imgid;

    /**
     * Table:     tag_fo_img
     * Column:    tagId
     * Nullable:  false
     */
    private Long tagid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tag_fo_img
     *
     * @mbg.generated Tue Jul 19 12:04:09 CST 2022
     */
    private static final long serialVersionUID = 1L;
}