package com.github.shby0527.tgbot.entities;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * 表名: tg_uploaded
 * 创建时间: 2022-07-19 12:04:09
 */
@Data
public class TgUploaded implements Serializable {
    /**
     * Table:     tg_uploaded
     * Column:    imgId
     * Nullable:  false
     */
    private Long imgid;

    /**
     * Table:     tg_uploaded
     * Column:    tgId
     * Nullable:  false
     */
    private String tgid;

    private String filePath;

    private Integer httpCode;

    /**
     * Table:     tg_uploaded
     * Column:    status
     * Nullable:  true
     */
    private Byte status;

    /**
     * Table:     tg_uploaded
     * Column:    ctime
     * Nullable:  true
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tg_uploaded
     *
     * @mbg.generated Tue Jul 19 12:04:09 CST 2022
     */
    private static final long serialVersionUID = 1L;
}