package com.github.shby0527.tgbot.entities;

import lombok.Data;

import java.io.Serializable;

/**
 * 表名: userInfo
 * 创建时间: 2022-08-16 17:58:22
 */
@Data
public class Userinfo implements Serializable {
    /**
     * 用户ID
     * <p>
     * Table:     userInfo
     * Column:    id
     * Nullable:  false
     */
    private Long id;

    /**
     * 姓名
     * <p>
     * Table:     userInfo
     * Column:    firstName
     * Nullable:  true
     */
    private String firstname;

    /**
     * Table:     userInfo
     * Column:    lastName
     * Nullable:  true
     */
    private String lastname;

    private String languageCode;

    /**
     * 0: 普通人， 1: 管理，可以使用一些管理指令, 2: own 可以无限制使用所有指令
     * <p>
     * Table:     userInfo
     * Column:    permission
     * Nullable:  true
     */
    private Integer permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userInfo
     *
     * @mbg.generated Tue Aug 16 17:58:22 CST 2022
     */
    private static final long serialVersionUID = 1L;
}