package com.github.shby0527.tgbot.entities;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * 表名: UserJobs
 * 创建时间: 2022-08-17 17:25:49
 */
@Data
public class Userjobs implements Serializable {
    /**
     * 主键
     *
     * Table:     UserJobs
     * Column:    id
     * Nullable:  false
     */
    private Long id;

    /**
     * 用户ID
     *
     * Table:     UserJobs
     * Column:    userid
     * Nullable:  false
     */
    private Long userid;

    /**
     * 名称
     *
     * Table:     UserJobs
     * Column:    name
     * Nullable:  false
     */
    private String name;

    /**
     * 消息发送到的chatid
     *
     * Table:     UserJobs
     * Column:    chatid
     * Nullable:  false
     */
    private Long chatid;

    /**
     * 调度服务名称
     *
     * Table:     UserJobs
     * Column:    scheduler
     * Nullable:  false
     */
    private String scheduler;

    /**
     * 参数
     *
     * Table:     UserJobs
     * Column:    arguments
     * Nullable:  true
     */
    private String arguments;

    /**
     * corn表达式/iso durtion 表达式
     *
     * Table:     UserJobs
     * Column:    corn
     * Nullable:  false
     */
    private String corn;

    /**
     * 下一次的时间戳
     *
     * Table:     UserJobs
     * Column:    nextTruck
     * Nullable:  false
     */
    private Long nexttruck;

    /**
     * 创建时间
     *
     * Table:     UserJobs
     * Column:    ctime
     * Nullable:  false
     */
    private Date ctime;

    /**
     * 最后更新时间
     *
     * Table:     UserJobs
     * Column:    mtime
     * Nullable:  false
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UserJobs
     *
     * @mbg.generated Wed Aug 17 17:25:49 CST 2022
     */
    private static final long serialVersionUID = 1L;
}